project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!files/"
  resources:
    - "*.json"
    - "files"
    - "_extensions"

execute:
  freeze: auto


website:
  repo-url: https://github.com/inqs909/m398_f26
  title: "MATH 398"
  site-url: www.inqs.info/m398_f26
  favicon: img/logo.png
  navbar:
    logo: img/logo.png
    right:
      - syllabus.qmd
      - lectures.qmd
      - project_report.qmd
      - python.qmd
      - books.qmd


format:
  html:
    theme:
      light: themes.scss
    toc: true


